name: demo pipeline
on: 
    push: 
        branches:
            - main
            - dev
    pull_request:
        branches: [ main, dev ]
    schedule:
        - cron: "*/1 * * * *"
jobs:
    setup_job:
        runs-on: ubuntu-latest      # macos-latest, windows-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: create file
              run: | 
               touch github-action.txt 
               ls -la
               echo "Hello World!"
               cat README.md
        needs: 
            - build_job
            - build_job
    build_job:
        runs-on: windows-latest
        steps:
            - name: display hello
              run: echo hello Wolrd from Windows
            - name: Display github action.txt file
              run: cat github-action.txt
    deploy_job:
        needs:
            - setup_job
        runs-on: macos-latest
        steps:
            - run: echo "ello Mac"
